###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      volumes:
        - .:/var/www/html/immedia
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=immedia
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: immedia-webserver
      working_dir: /var/www/html/immedia
      volumes:
          - ./src:/var/www/html
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: immeida-php-fpm
      working_dir: /var/www/html/immedia
      volumes:
        - ./src:/var/www/html
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

